#!/bin/bash
# =========================================================================
# EVALUACIÓN: GIT CON BASH - SISTEMAS OPERATIVOS
# ESTUDIANTE:Noel Sierra
# CÉDULA: 32049955
# CORREO: Noeldavidsierra@gmail.com
# TEMA: Fundamentos del Hardware (CPU, RAM, discos y perifericos) 
# =========================================================================

echo "========================================================================="
echo "1. INTRODUCCIÓN A LOS FUNDAMENTOS DE HARDWARE"
echo "========================================================================="
echo "El hardware representa los componentes físicos y tangibles de un sistema"
echo "informático. Su función principal es proporcionar la infraestructura"
echo "necesaria para que el sistema operativo y el software de aplicación"
echo "puedan ejecutar instrucciones y procesar datos. Comprender el hardware"
echo "es crucial en la gestión de sistemas, ya que el rendimiento, la"
echo "estabilidad y la eficiencia de los algoritmos dependen directamente"
echo "de la interacción óptima entre los recursos físicos y el código."
echo ""
echo "Los pilares esenciales del hardware se dividen en cuatro áreas principales:"
echo "La Unidad Central de Procesamiento (CPU), la Memoria de Acceso Aleatorio"
echo "(RAM), los sistemas de almacenamiento masivo (Discos) y los dispositivos"
echo "de interacción externa (Periféricos)."
echo ""

echo "========================================================================="
echo "2. LA UNIDAD CENTRAL DE PROCESAMIENTO (CPU)"
echo "========================================================================="
echo "La CPU es el cerebro del computador, encargada de interpretar y ejecutar"
echo "las instrucciones de los programas mediante ciclos de lectura, decodificación"
echo "y ejecución de datos."
echo ""
echo "* Características:"
echo "  - Velocidad de Relioj: Medida en Gigahertz (GHz), indica cuántos ciclos"
echo "    de procesamiento puede realizar por segundo."
echo "  - Núcleos e Hilos: Permiten la ejecución simultánea de múltiples tareas"
echo "    (Multiprocesamiento y Multithreading)."
echo "  - Memoria Caché: Niveles de memoria ultra rápida (L1, L2, L3) internos"
echo "    en el chip para almacenar datos de uso frecuente."
echo ""
echo "* Ventajas:"
echo "  - Alta velocidad de procesamiento para operaciones lógico-matemáticas."
echo "  - Capacidad de paralelizar procesos complejos en sistemas modernos."
echo ""
echo "* Desventajas:"
echo "  - Generación de calor elevado que requiere sistemas de enfriamiento."
echo "  - Su velocidad se ve limitada si los demás componentes (RAM/Disco)"
echo "    provocan un cuello de botella."
echo ""

echo "========================================================================="
echo "3. MEMORIA DE ACCESO ALEATORIO (RAM)"
echo "========================================================================="
echo "La RAM es la memoria de trabajo volátil del sistema. Almacena de forma"
echo "temporal los datos y programas que la CPU está procesando activamente en"
echo "el momento."
echo ""
echo "* Características:"
echo "  - Volatilidad: Pierde absolutamente toda la información guardada"
echo "    cuando el dispositivo se apaga o se reinicia."
echo "  - Velocidad y Latencia: Ofrece tasas de transferencia de datos muy altas"
echo "    en comparación con los sistemas de almacenamiento."
echo ""
echo "* Ventajas:"
echo "  - Permite un acceso inmediato y aleatorio a cualquier celda de memoria"
echo "    sin penalización de tiempo."
echo "  - Crucial para la fluidez del sistema multitarea."
echo ""
echo "* Desventajas:"
echo "  - Capacidad limitada y costo por gigabyte significativamente más alto"
echo "    que el almacenamiento secundario."
echo "  - No sirve para guardar archivos de forma permanente debido a su volatilidad."
echo ""

echo "========================================================================="
echo "4. DISCO DE ALMACENAMIENTO (HDD / SSD)"
echo "========================================================================="
echo "Son los encargados del almacenamiento secundario no volátil, manteniendo"
echo "resguardados los datos, el sistema operativo y las aplicaciones de forma"
echo "permanente, incluso sin energía eléctrica."
echo ""
echo "* Características:"
echo "  - Mecánicos (HDD): Utilizan platos magnéticos giratorios y cabezales lectores."
echo "  - Estado Sólido (SSD): Utilizan memoria flash interconectada, eliminando"
echo "    partes móviles y multiplicando la velocidad."
echo ""
echo "* Ventajas:"
echo "  - Altas capacidades de almacenamiento (Terabytes) a costos accesibles."
echo "  - Retención permanente y segura de los datos del usuario."
echo ""
echo "* Desventajas:"
echo "  - Los HDD son susceptibles a fallos mecánicos por impactos o desgaste."
echo "  - Aunque los SSD son rápidos, siguen siendo notablemente más lentos"
echo "    en tiempos de acceso si se comparan directamente con la memoria RAM."
echo ""

echo "========================================================================="
echo "5. PERIFÉRICOS"
echo "========================================================================="
echo "Son las unidades o dispositivos de hardware a través de los cuales la"
echo "computadora se comunica con el mundo exterior (usuarios, redes u otros"
echo "sistemas)."
echo ""
echo "* Características:"
echo "  - Periféricos de Entrada: Capturan datos externos (Teclado, ratón, cámaras)."
echo "  - Periféricos de Salida: Proyectan o muestran información procesada"
echo "    (Monitores, impresoras, cornetas)."
echo "  - Periféricos Mixtos/E/S: Cumplen ambas funciones (Pantallas táctiles,"
echo "    tarjetas de red, unidades de almacenamiento USB externas)."
echo ""
echo "* Ventajas:"
echo "  - Permiten la adaptabilidad y personalización del equipo según las"
echo "    necesidades específicas del usuario."
echo "  - Facilitan la interacción intuitiva humano-computador."
echo ""
echo "* Desventajas:"
echo "  - Dependencia estricta de controladores de software (drivers) actualizados"
echo "    for su correcto funcionamiento en el sistema operativo."
echo "  - Incrementan el consumo energético global y los puntos posibles de"
echo "    falla de hardware externo."
echo "========================================================================="
read -p "Presione Enter para salir..."
